const ScreenNames = {
  LOGIN: 'Login',
  HOME: 'Home',
  WELCOME: 'Welcome',
  SIGNUP: 'Signup',
  TERMSANDCONDITIONS: 'TermsAndConditions',
  PRIVACYPOLICY: 'PrivacyPolicy',
  CHOOSECATEGORY: 'ChooseCategory',
  CATEGORYDESCRIPTION: 'CategoryDescription',
  WELCOMEPROFILE: 'WelcomeProfile',
  MANAGELOCATION: 'ManageLocation',
  IMAGEGALLERY: 'ImageGallery',
  USERPROFILEPINSTAR: 'UserProfilePinstar',
  CREATELOOKBOOK: 'CreateLookbook',
  ADDPHOTOSTOLOOKBOOK: 'AddPhotosToLookbook',
  VIEWLOOKBOOK: 'ViewLookbook',
  VIEWLOOKBOOKIMAGE: 'ViewLookbookImage',
  MYAllLOOKBOOKS: 'MyAllLookbooks',
  PINSTARDASHBOARD: 'PinstarDashboardScreen',
  PINSTARCOMMUNITY: "PinstarCommunity",
  PINSTARYAYORNAY: "PinstarYayorNay",
}
export default ScreenNames;