export { default as LoginScreen } from './login'
export { default as WelcomeScreen } from './welcome'
export { default as SignupScreen } from './signup'
export { default as TermsandConditionsScreen } from './termsAndConditions'
export { default as PrivacyPolicyScreen } from './privacyPolicy'
